### ISSUE TITLE
Place in quadrant settings

### ISSUE THREAD

**Issue by funinthefalls** [openhardwarecoza/LaserWeb2#39] opened 2016-05-03 21:34 UTC
When I set the quadrant to top left, SVG files are placed correctly, but bitmaps still place in bottom left.

**Comment by ghost** [comment] 2016-05-04 07:27
Only SVG(preview) and DXF(preview and resultant gcode) have been implemented for this so far

Duplicate of #31  and #28

**Closed as completed by ghost** 2016-05-04 07:27 UTC

**Comment by funinthefalls** [comment] 2016-05-05 15:01
Sorry buddy, didn't see those ones.
