### ISSUE TITLE
Recalculating rasters

### ISSUE THREAD

**Issue by funinthefalls** [openhardwarecoza/LaserWeb2#63] opened 2016-05-25 06:56 UTC
If I open a bitmap and generate the raster, then change the dpi and re generate the raster, it overlays the new view over the original view.

**Comment by ghost** [comment] 2016-05-25 08:34
Duplicate of #48

**Comment by funinthefalls** [comment] 2016-05-25 12:05
It is not the gcode that was the problem, it was the preview image. Not sure if that makes a difference to you.

**Comment by ghost** [comment] 2016-05-25 12:21
I tested twice, can't replicate...

Check if its still happening? Screenshot might be helpful if it does

**Comment by cojarbi** [comment] 2016-05-25 12:36
Not sure if this applies but, raster and then load an svg
<img width="1861" alt="screen shot 2016-05-25 at 7 34 58 am" src="https://cloud.githubusercontent.com/assets/16444438/15540065/52bb8044-224b-11e6-96eb-3f5122706cf4.png">

**Comment by ghost** [comment] 2016-05-25 12:40
The svg cleanup is your old ticket i am quite sure

**Comment by cojarbi** [comment] 2016-05-25 12:54
Ok so i believe @funinthefalls is talking about this, but it shows the preview over/behind the the old raster preview but once generated it disappear  
<img width="1860" alt="screen shot 2016-05-25 at 7 52 06 am" src="https://cloud.githubusercontent.com/assets/16444438/15540566/b7e82eac-224d-11e6-8da4-25156e1f5ee0.png">

**Comment by ghost** [comment] 2016-05-25 12:55
Oh right,  yes thats whats going on.   I show the gcode.  Until you
generate gcode...  So you want me to clear the gcode as soon as you change
the DPI?

**Comment by funinthefalls** [comment] 2016-05-25 12:56
@cojarbi That is exactly what I was seeing. I think clearing the gcode when changing the dpi would be nice, if it does not hinder performance. Seeing the double images might confuse us lesser mortals. :)

**Comment by cojarbi** [comment] 2016-05-25 13:21
Think of it for a second, having the previous code gives you a compare over the previous size,  etc. Could be beneficial maybe on small complicated arts. It does fell weird I agree.

**Comment by cojarbi** [comment] 2016-05-25 13:28
Forget it, would only help when enlarging over the previous one not the other way arround

**Comment by cojarbi** [comment] 2016-05-25 13:35
Unless there is some black magic the will bring the new one forward or back on the screen.  This could be good when the live feed from the camera is working for testing perfect placement

**Comment by funinthefalls** [comment] 2016-05-25 13:53
Will test later today, will be out of my office for most of the day.

**Comment by ghost** [comment] 2016-05-25 13:58
Ok clearing gcode when you change dpi...

**Closed as completed by ghost** 2016-05-25 13:58 UTC

**Comment by funinthefalls** [comment] 2016-05-25 20:03
Thanks Peter
