### ISSUE TITLE
Position 0,0 top left of file?

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb2#7] opened 2016-03-24 02:51 UTC
<img width="1620" alt="screen shot 2016-03-23 at 9 50 25 pm" src="https://cloud.githubusercontent.com/assets/16444438/14007091/591a04f0-f141-11e5-8bbf-9a326cb461e6.png">

**Comment by cojarbi** [comment] 2016-03-24 03:34
Location seems to be off once imported no matter where is located in the file ( evenif  illustrator and inkscape location is 0,0 )

Generating code for svg also shows preview off from the imported file.

First laser ON seems lower left of square, that seems to match the path preview generated by LW
G1 F3200 X92.465 Y155.096 S255
<img width="1612" alt="screen shot 2016-03-23 at 10 32 40 pm" src="https://cloud.githubusercontent.com/assets/16444438/14007715/321e03fa-f147-11e5-8c25-be92977ce350.png">
[svg gcode off.txt](https://github.com/openhardwarecoza/LaserWeb2/files/187219/svg.gcode.off.txt)

**Comment by ghost** [comment] 2016-03-24 04:38
Already an open issue (:

I havent coded in position at all.  The idea is to look at a bounding box
of the imported three.js object,  see how far away from 0,0 is is.  Then
translate the object.  Store that initial translation values in an array
and then account for it when scaling/moving object.

**Comment by ghost** [comment] 2016-03-24 09:19
Duplicate of #4

But I also pushed some code this morning that fixes it for DXFs.  Just note the position boxes at the bottom right:  After placing it on 0,0 they already contain real world values . I'll improve that a bit later

0,0 for SVG works for the inital object but generating gcode places the gcode in the wrong space (svg has 0,0 as top left, everything else has 0,0 bottom left - so a lot of extra code to flip the offset etc needed

**Closed as completed** 2016-03-24 09:19 UTC

**Comment by cojarbi** [comment] 2016-03-24 11:14
Woops. Sorry by know you.would think that I'm reading previous issues? I am :)

Saludos / Regards

Ariel Yahni
